### ISSUE TITLE
pubsub connection refused

### ISSUE THREAD

**Issue by marwan-at-work** [GoogleCloudPlatform/cloud-sdk-docker#104]
i have the following compose file:

```
version: "3.3"
services:
  dev:
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    ports:
      - '3000:3000'
    environment:
      - PUBSUB_EMULATOR_HOST=http://pubsub:8085
      - PUBSUB_PROJECT_ID=marwan-test
    depends_on:
      - pubsub
  pubsub:
    image: google/cloud-sdk
    ports:
      - '8085:8085'
    command: ["gcloud", "beta", "emulators", "pubsub", "start"]
```

When I `docker exec -it <id> /bin/bash` into my `dev` container, and `curl pubsub:8085` i get a connection refused. However, if I exec into the `pubsub` container, the `curl localhost:8085` returns OK. 

It might be useful to mention that I also cannot `curl localhost:8085` from the host machine. I don't get a connection refused, instead I get an `empty response`. 

Am I missing something here? 

Thanks!
