### ISSUE TITLE
Datastore emulator cannot find JAVA any longer

### ISSUE THREAD

**Issue by irri** [GoogleCloudPlatform/cloud-sdk-docker#146]
It has been working fine for a long time. This docker image is part of my CI pipeline. But suddenly today when trying to start the Datastore Emulator this happens:

>ERROR: (gcloud.beta.emulators.datastore.start) The java executable on your PATH is not a Java 8+ JRE. The Google Cloud Datastore emulator requires a Java 8+ JRE installed and on your system PATH

Actual code snipped from `Drone CI` yaml file:
```
services:
  datastore:
    image: google/cloud-sdk
    command: ["gcloud", "beta", "emulators", "datastore", "start", "--host-port", "0.0.0.0:8081", "--no-store-on-disk", "--consistency", "1"]
```

Anyone else experienced this?
