### ISSUE TITLE
PubSub Emulator Can't Start on version 314

### ISSUE THREAD

**Issue by restuhaqza** [GoogleCloudPlatform/cloud-sdk-docker#228]
Hi all, I created a new container for `pubsub-emulator` using this image. using latest image (314) but I got an error when trying run the container with entrypoint `gcloud beta emulators pubsub start --host-port=0.0.0.0:8085` like this :
```
You need the [pubsub-emulator] component to use the Google Cloud 
Pub/Sub emulator.
ERROR: (gcloud.beta.emulators.pubsub.start) 
You cannot perform this action because the Cloud SDK component manager 
is disabled for this installation. You can run the following command 
to achieve the same result for this installation: 
sudo apt-get install google-cloud-sdk-pubsub-emulator
```
My old configuration for docker compose is :

```
 pubsub-emulator:
    container_name: pubsub-emulator
    image: google/cloud-sdk:latest
    ports:
      - '8085:8085'
    expose:
      - '8085'
    environment:
      - INSTALL_COMPONENTS=google-cloud-sdk-pubsub-emulator
    entrypoint: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    networks:
      - net
```

So, I solved this case using the previous version like this:
```
pubsub-emulator:
    container_name: pubsub-emulator
    image: google/cloud-sdk:313.0.1
    ports:
      - '8085:8085'
    expose:
      - '8085'
    environment:
      - INSTALL_COMPONENTS=google-cloud-sdk-pubsub-emulator
    entrypoint: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    networks:
      - net
```

My question is how to configure pubsub-emulator on latest image?
