### ISSUE TITLE
cloud-pubsub-emulator error 'Failed to load class "org.slf4j.impl.StaticLoggerBinder'

### ISSUE THREAD

**Issue by davidjb99** [GoogleCloudPlatform/cloud-sdk-docker#260]
Hi, 

When using the `gcr.io/google.com/cloudsdktool/cloud-sdk:emulators` image and specifying a custom port for cloud-pubsub-emulator I get the following error, I get a similar error with the default port. I'm running this via docker-compose  

Custom port
```
  cloud-pub-sub:
    build:
      context: ./
      dockerfile: Dockerfile.cloudPubSub
      network: host

    container_name: cloud-pub-sub
    ports:
      - "8086:8086"

    command: gcloud --quiet beta emulators pubsub start --project=tokyo-rain-123 --host-port=8086

```

```
cloud-pub-sub  | Executing: /google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=8086
cloud-pub-sub  | [pubsub] This is the Google Pub/Sub fake.
cloud-pub-sub  | [pubsub] Implementation may be incomplete or differ from the real system.
cloud-pub-sub  | [pubsub] Dec 09, 2021 1:54:40 PM com.google.cloud.pubsub.testing.v1.Main main
cloud-pub-sub  | [pubsub] INFO: IAM integration is disabled. IAM policy methods and ACL checks are not supported
cloud-pub-sub  | [pubsub] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
cloud-pub-sub  | [pubsub] SLF4J: Defaulting to no-operation (NOP) logger implementation
cloud-pub-sub  | [pubsub] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
cloud-pub-sub  | [pubsub] Exception in thread "main" java.io.IOException: Failed to bind to address /0.0.31.150:0
cloud-pub-sub  | [pubsub] 	at io.grpc.netty.NettyServer.start(NettyServer.java:268)
cloud-pub-sub  | [pubsub] 	at io.grpc.internal.ServerImpl.start(ServerImpl.java:183)
cloud-pub-sub  | [pubsub] 	at io.grpc.internal.ServerImpl.start(ServerImpl.java:90)
cloud-pub-sub  | [pubsub] 	at io.gapi.emulators.grpc.GrpcServer.start(GrpcServer.java:178)
cloud-pub-sub  | [pubsub] 	at com.google.cloud.pubsub.testing.v1.Main.main(Main.java:223)
cloud-pub-sub  | [pubsub] Caused by: java.net.BindException: Cannot assign requested address
cloud-pub-sub  | [pubsub] 	at java.base/sun.nio.ch.Net.bind0(Native Method)
cloud-pub-sub  | [pubsub] 	at java.base/sun.nio.ch.Net.bind(Net.java:455)
cloud-pub-sub  | [pubsub] 	at java.base/sun.nio.ch.Net.bind(Net.java:447)
cloud-pub-sub  | [pubsub] 	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
cloud-pub-sub  | [pubsub] 	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
cloud-pub-sub  | [pubsub] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:550)
cloud-pub-sub  | [pubsub] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
cloud-pub-sub  | [pubsub] 	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
cloud-pub-sub  | [pubsub] 	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
cloud-pub-sub  | [pubsub] 	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
cloud-pub-sub  | [pubsub] 	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248)
cloud-pub-sub  | [pubsub] 	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
cloud-pub-sub  | [pubsub] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
cloud-pub-sub  | [pubsub] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
cloud-pub-sub  | [pubsub] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
cloud-pub-sub  | [pubsub] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
cloud-pub-sub  | [pubsub] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
cloud-pub-sub  | [pubsub] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
cloud-pub-sub  | [pubsub] 	at java.base/java.lang.Thread.run(Thread.java:829)
^CGracefully stopping... (press Ctrl+C again to force)
```

With default port
```
cloud-pub-sub:
    build:
      context: ./
      dockerfile: Dockerfile.cloudPubSub
      network: host

    container_name: cloud-pub-sub
    ports:
      - "8085:8085"

    command: gcloud --quiet beta emulators pubsub start --project=tokyo-rain-123
```

```
cloud-pub-sub  | Executing: /google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=localhost --port=8085
cloud-pub-sub  | [pubsub] This is the Google Pub/Sub fake.
cloud-pub-sub  | [pubsub] Implementation may be incomplete or differ from the real system.
cloud-pub-sub  | [pubsub] Dec 09, 2021 2:02:45 PM com.google.cloud.pubsub.testing.v1.Main main
cloud-pub-sub  | [pubsub] INFO: IAM integration is disabled. IAM policy methods and ACL checks are not supported
cloud-pub-sub  | [pubsub] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
cloud-pub-sub  | [pubsub] SLF4J: Defaulting to no-operation (NOP) logger implementation
cloud-pub-sub  | [pubsub] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
cloud-pub-sub  | [pubsub] Dec 09, 2021 2:02:47 PM com.google.cloud.pubsub.testing.v1.Main main
cloud-pub-sub  | [pubsub] INFO: Server started, listening on 8085
```
