### ISSUE TITLE
emulators firestore lost connection when cloud build run

### ISSUE THREAD

**Issue by tttmaximttt** [GoogleCloudPlatform/cloud-sdk-docker#315]
emulators firestore lost connection when cloud build run

```yaml
version: '3.7'
networks:
  default:
    external:
      name: cloudbuild
services:
  firestore:
    image: google/cloud-sdk:latest
    ports:
      - '9090:9090'
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:9090
    healthcheck:
      test: [ "CMD", "curl", "-f", "0.0.0.0:9090" ]
      interval: 30s
      timeout: 10s
      retries: 5
```

`FIRESTORE_EMULATOR_HOST=0.0.0.0:9090` - exported

firestore admin tryes to connect to this host and get error
`14 UNAVAILABLE: No connection established`
