### ISSUE TITLE
Pubsub shutdown time

### ISSUE THREAD

**Issue by marco-scoppetta-qatalog** [GoogleCloudPlatform/cloud-sdk-docker#340]
Hi all,

We've tried the PubSub emulator, which is starting and shutting down just fine (with Ctrl+C).

When using the Dockerised version, we're seeing a fixed 10 seconds time out before the emulator is actually stopped.

This is the Docker compose part concerning the pubsub:
```
pubsub:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --project=xxx
    ports:
      - '8085:8085'
 ```
 
When running `docker-compose down` all the other containers are immediately stopped, whereas the pubsub one seems to have some sort of timeout that needs to expire before shutting down:
 
 
<img width="1439" alt="image" src="https://github.com/GoogleCloudPlatform/cloud-sdk-docker/assets/60605762/6ddae856-4742-4c73-83bf-8baa7b2778c8">

Is this expected, are we doing something wrong, or is there any setting we can tweak for it to shutdown immediately?

Thanks!
