### ISSUE TITLE
Datastore emulator cannot find JAVA any longer from 523.0.0

### ISSUE THREAD

**Issue by FukkinHikidashi** [GoogleCloudPlatform/cloud-sdk-docker#559]
It has been working fine for a long time. This docker image is part of my CI pipeline. But suddenly today when trying to start the Datastore Emulator this happens:

```
datastore                                         | ERROR: (gcloud.beta.emulators.datastore.start) The java executable on your PATH is not a Java 21+ JRE. The Google Cloud Datastore emulator requires a Java 21+ JRE installed and on your system PATH
```

I use this image in docker-compose like this.

```
services:
  datastore:
    container_name: 'datastore'
    image: google/cloud-sdk:latest
    command: gcloud beta emulators datastore start --project=datastore --host-port=0.0.0.0:8082 --use-firestore-in-datastore-mode
```

When I specify the version `552.0.0`, it runs.
```
image: google/cloud-sdk:552.0.0
```

It might be similar to this issue.
https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/146
