### ISSUE TITLE
unable to upload mycustom image to a container registry using google/cloud-sdk docker image

### ISSUE THREAD

**Issue by gudurisaiteja** [GoogleCloudPlatform/cloud-sdk-docker#92]
Hey,
I'm using google/cloud-sdk docker image for deployment.
so I need to upload mycustom image to a container registry.

gcloud docker -- push gcr.io/${PROJECT_ID}/helloworld:v1
How can you support above command using google/cloud-sdk ?

**Comment by ahmetb** [comment]
`gcloud docker` command actually calls the `docker` command under the covers, which requires a `docker-engine` daemon to be reachable/preconfigured. Inside the container, you most likely will not have a docker daemon running. (You might consider solutions like dind, but I wouldn't recommend as it would be a very complicated solution.)

I recommend installing gcloud SDK directly on your machine and not using this image for this purpose.

**Comment by ahmetb** [comment]
Actually mounting the `/var/run/docker.sock` inside the container might work, but I'm not certain what sort of caveats it has. In that case, you'd still need to extend this image and install docker-cli yourself.

**Comment by gudurisaiteja** [comment]
Thanks for that.

**Comment by ahmetb** [comment]
Also, if you need `gcloud docker -- push` just because `docker push` directly doesn't work on your host, you can mount the ~/.dockercfg file (or ~/.docker directory) inside the container and run:

    gcloud docker -a

This will modify the docker "client" config file on your host and configure short-lived tokens for GCR, so you can directly use "docker push" with gcr. This can work fine for CI/CD systems

**Comment by gudurisaiteja** [comment]
I will give a try on this. Thanks for suggesting this option.

**Comment by MrSaints** [comment]
It's also possible to authenticate using a service account JSON key. I use the following for GitLab CI / CD:

```
docker login -u _json_key -p "service_account.json" https://gcr.io
```

`service_account.json` can be _created_ using their secret variables feature.

**Comment by remcohaszing** [comment]
Did anyone get this to work? I like the solution proposed by @MrSaints, but it doesn’t work for all situations, i.e. if the Docker image is built in a previous step, but the service account JSON key is accessible only to a specific environment.

```yaml
deploy review:
  image: google/cloud-sdk:339.0.0-alpine
  rules:
    - if: $CI_MERGE_REQUEST_IID
  services:
    - docker: dind
  environment:
    name: review/$CI_MERGE_REQUEST_IID
    on_stop: stop review
  script:
    - gcloud auth activate-service-account --key-file "$GCLOUD_KEY"
    - gcloud auth configure-docker
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    # followed by some gcloud run commands
```

The last command fails with:

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
